<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tab6</name>
   <tag></tag>
   <elementGuidId>11ee52e1-44eb-4e3c-b83c-7cf1df8c42ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='lsq-form-custom-tab-list-tab6']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Tab6&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df7e099c-4121-45c2-a172-0eda9640dbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab6</value>
      <webElementGuid>dd9add68-630f-42a0-89c6-624eeade5919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b02cc69a-6697-4b3d-800d-079474d53057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-old-value</name>
      <type>Main</type>
      <value>Tab6</value>
      <webElementGuid>edb5eea6-d463-40a9-ac1b-250b779ab741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tab6</value>
      <webElementGuid>be1c9b05-4cb6-4228-bf57-2c70b2355cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tab6</value>
      <webElementGuid>58e4e976-7395-4910-bfc3-8bb2f8c95073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-custom-tab-list-tab6&quot;)/a[1]</value>
      <webElementGuid>01c560a5-493b-41f7-a6f7-81294d218a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_b2aa29</value>
      <webElementGuid>07d05851-2228-41ce-b6e6-d61bedea1cad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='lsq-form-custom-tab-list-tab6']/a</value>
      <webElementGuid>8b61540e-b1df-49cd-add0-9f9f59dac8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tab6')]</value>
      <webElementGuid>54026255-4f08-47dd-89d5-68126a42dccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab3'])[1]/following::a[1]</value>
      <webElementGuid>a5bf0ae2-64b9-4e11-9f0e-4c323e93cdf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hidden Tab'])[1]/following::a[2]</value>
      <webElementGuid>3d2c93d2-b0cf-4bd7-98e1-a113dbc77334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab7'])[1]/preceding::a[1]</value>
      <webElementGuid>e126aa68-4594-4e6d-a842-069eef5fc157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab8'])[1]/preceding::a[2]</value>
      <webElementGuid>d1202b63-ebf0-43b6-a304-90e445106940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tab6']/parent::*</value>
      <webElementGuid>e9710034-5b82-4963-a53b-53442d11001f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab6')]</value>
      <webElementGuid>9758b93f-a0b5-4940-9e8c-16b3d48e3144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>1942ef3f-5de6-4f69-8635-5edf5be0008f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab6' and @title = 'Tab6' and (text() = 'Tab6' or . = 'Tab6')]</value>
      <webElementGuid>2c645eea-7010-4fac-9da8-4047890dd5fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
