<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tab6 (1)</name>
   <tag></tag>
   <elementGuidId>67171d0d-84ec-4dc5-80b0-4c69fd8fca23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='lsq-form-custom-tab-list-tab6']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Tab6&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c3de03e-056f-487d-bed2-3a8d1c210329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab6</value>
      <webElementGuid>3d2281c7-28d3-4816-b9a5-4c4ddad0cd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>0b026e14-f09b-40ab-9b40-81865196d35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-old-value</name>
      <type>Main</type>
      <value>Tab6</value>
      <webElementGuid>f2f5c0d5-848f-4566-91bc-9fc9c95e9193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tab6</value>
      <webElementGuid>d469fc5f-f3c6-4364-90f7-9a85d15bafbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tab6</value>
      <webElementGuid>5e9a8ffb-fa5d-4920-baa3-7fdb5a789dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-custom-tab-list-tab6&quot;)/a[1]</value>
      <webElementGuid>11ec2d89-687d-489f-b1fa-a7c3a6bbc9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_9ae9be</value>
      <webElementGuid>6a452621-3472-43ab-bd50-d19c98adbb61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='lsq-form-custom-tab-list-tab6']/a</value>
      <webElementGuid>328aeb09-276e-495d-af34-548db14089a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tab6')]</value>
      <webElementGuid>feb71c5c-609b-4138-b73f-235dff662315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab3'])[1]/following::a[1]</value>
      <webElementGuid>70063e8a-afa3-4c87-90aa-5c5552bb8d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hidden Tab'])[1]/following::a[2]</value>
      <webElementGuid>0152bd34-3fd0-45c9-a177-bb5835811878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab7'])[1]/preceding::a[1]</value>
      <webElementGuid>97b7e01c-ac6e-49e5-a4ae-0a0df8b220d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab8'])[1]/preceding::a[2]</value>
      <webElementGuid>2257d7c8-63d1-422b-beaa-73e521c5ce0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tab6']/parent::*</value>
      <webElementGuid>b940d525-816c-4177-981f-8a3ca0a569ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab6')]</value>
      <webElementGuid>b48b6b30-0d5a-4ed9-a1bb-8cd24eb67094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>8722c1a1-d156-4f3b-b5c5-5044e3263f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab6' and @title = 'Tab6' and (text() = 'Tab6' or . = 'Tab6')]</value>
      <webElementGuid>39e6b0fb-daa8-4492-87f3-f7181aa62129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
