<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tab3</name>
   <tag></tag>
   <elementGuidId>c65a2046-a3d9-457c-9fd1-c592193aecf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='lsq-form-custom-tab-list-tab3']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Tab3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3266dbb3-2e15-48e0-826c-ff071441f3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab3</value>
      <webElementGuid>4ec799f8-6e50-4646-854a-5c961a3f21bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f9b2030c-5b17-47ba-ab61-02eb7f8e4675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-old-value</name>
      <type>Main</type>
      <value>Tab3</value>
      <webElementGuid>0b016ff7-5e32-4cb6-a028-fa2f4fa11a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tab3</value>
      <webElementGuid>f71773ad-78f3-4237-b817-05f8c9590c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tab3</value>
      <webElementGuid>d9854fd7-1956-49a6-a622-d4d8c144be97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-custom-tab-list-tab3&quot;)/a[1]</value>
      <webElementGuid>2fd8b675-1e86-4647-8adc-a9428af4f1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_b2aa29</value>
      <webElementGuid>229d8a56-9d7e-4a43-9fc2-8c31c2e6ad2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='lsq-form-custom-tab-list-tab3']/a</value>
      <webElementGuid>baef5495-fe4f-4c0c-89aa-715bf1e363aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tab3')]</value>
      <webElementGuid>63d481c4-384b-46b3-82ee-f95509c1cf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hidden Tab'])[1]/following::a[1]</value>
      <webElementGuid>394d4a99-d303-44fa-a861-6cb7397baf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab6'])[1]/preceding::a[1]</value>
      <webElementGuid>4a75702e-e782-40bc-8989-ea3d62bfc3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab7'])[1]/preceding::a[2]</value>
      <webElementGuid>59e51560-3b6e-4fbe-ab95-0611679b15c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tab3']/parent::*</value>
      <webElementGuid>4889bca7-1cec-4b69-9d0e-12d32d5d4932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab3')]</value>
      <webElementGuid>c271d421-5c68-4a63-a23a-4eba8b9578b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>94f941b0-3094-4a29-9f7c-23d8985b991a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab3' and @title = 'Tab3' and (text() = 'Tab3' or . = 'Tab3')]</value>
      <webElementGuid>765fecfc-76d2-4d5d-bbba-ac4a7191350c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
