<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tab8 (1)</name>
   <tag></tag>
   <elementGuidId>3c924006-6504-4b6b-ac78-d8ba2ba24ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='lsq-form-custom-tab-list-tab8']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Tab8&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8e36ebc-98f4-4bd5-892e-3ca20670cbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab8</value>
      <webElementGuid>23bfa3bd-e32f-467d-bfbf-347cecb014d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a21ecb52-eda4-4a7a-a8b3-56e5128ecf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-old-value</name>
      <type>Main</type>
      <value>Tab8</value>
      <webElementGuid>03817b85-9f03-4b49-99b4-34fb43f89e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tab8</value>
      <webElementGuid>c63e3e88-3bf8-4d55-a7bc-a909430fa6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tab8</value>
      <webElementGuid>85de0cb4-0d7d-4dfa-a192-b7939741f6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-custom-tab-list-tab8&quot;)/a[1]</value>
      <webElementGuid>faa8a482-83ee-4fe6-ab19-4bbc312cdc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_9ae9be</value>
      <webElementGuid>fc377d00-f343-4f88-bba6-b2b013a7d90b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='lsq-form-custom-tab-list-tab8']/a</value>
      <webElementGuid>ed728ac9-9b90-4a50-9036-26b956272e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tab8')]</value>
      <webElementGuid>70470586-0722-4dfc-979a-413d79b4f32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab7'])[1]/following::a[1]</value>
      <webElementGuid>d10ee6b0-b97e-4ede-be18-0e4eddc4cb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab6'])[1]/following::a[2]</value>
      <webElementGuid>1afd9b4c-697f-4435-8391-eb45f4425d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='expand_more'])[1]/preceding::a[1]</value>
      <webElementGuid>5f60ffcc-c674-4a74-b01e-df3dacf88c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tab8']/parent::*</value>
      <webElementGuid>ea284fd5-e1a5-4a68-9c4f-bceaf409bbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab8')]</value>
      <webElementGuid>534cf5df-ee6a-4c18-9f2f-854b60f6b7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>1db298b3-c1f0-4685-bb70-fc17123ee795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab8' and @title = 'Tab8' and (text() = 'Tab8' or . = 'Tab8')]</value>
      <webElementGuid>5b4ba5cc-dd82-4631-908c-b74beaecac45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
