<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tab8</name>
   <tag></tag>
   <elementGuidId>ed63fcc5-e148-4a9f-80c1-3b02e6a75ab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='lsq-form-custom-tab-list-tab8']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Tab8&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>938bbe20-3743-42f1-a015-2c02c321f140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab8</value>
      <webElementGuid>d9466f54-bb8b-407a-b866-ebaef7c1463b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3ecd6b8a-3878-4b20-ba01-d7e5252ce4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-old-value</name>
      <type>Main</type>
      <value>Tab8</value>
      <webElementGuid>59fa359d-0071-46ef-885a-95fdae9520c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tab8</value>
      <webElementGuid>b4d49518-b1df-4744-917f-3ddcee501bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tab8</value>
      <webElementGuid>1842fc16-d329-4825-8b9f-5d67e7e945eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-custom-tab-list-tab8&quot;)/a[1]</value>
      <webElementGuid>b23e3bc3-dac3-4296-b1bb-c4a97a72dd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_b2aa29</value>
      <webElementGuid>dc9a590e-d028-43ad-a130-4c80e85b4b2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='lsq-form-custom-tab-list-tab8']/a</value>
      <webElementGuid>3a4306b4-f2f3-472f-9bdd-0b6df0e46128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tab8')]</value>
      <webElementGuid>323f34a5-8a07-453c-847b-0d856e7f4a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab7'])[1]/following::a[1]</value>
      <webElementGuid>d90943c5-346e-49d5-9dc8-f8a2147e0eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab6'])[1]/following::a[2]</value>
      <webElementGuid>4eff87f4-26af-49ac-baf6-dba76152f938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='expand_more'])[1]/preceding::a[1]</value>
      <webElementGuid>c3fcc6ad-cd9a-4918-8aee-c9e4d261da9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tab8']/parent::*</value>
      <webElementGuid>6e9c14be-2b10-488d-8c61-b08ce9ad04a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab8')]</value>
      <webElementGuid>e430b0f9-69a7-4882-a13c-e96cce7e1ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>19b879e5-d06c-46eb-9706-820cbdf71158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#c0e9a917-c459-4fe4-9726-632b08e8b0ce_tab8' and @title = 'Tab8' and (text() = 'Tab8' or . = 'Tab8')]</value>
      <webElementGuid>f9903a07-eb20-42a9-b578-49bd32ce925c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
