<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test</name>
   <tag></tag>
   <elementGuidId>a10cf33a-b671-456e-88d1-8031f8f3ba85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;TestForm('c0e9a917-c459-4fe4-9726-632b08e8b0ce', false);&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd492f59-4d4d-4f9b-9ffd-84e524b9d28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small-x</value>
      <webElementGuid>493a2cf7-5b96-4c8d-9993-dad2b3db60be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6a2ca661-0ac1-412d-8374-e04b0a9388da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TestForm('c0e9a917-c459-4fe4-9726-632b08e8b0ce', false);</value>
      <webElementGuid>32192d38-da54-4de1-9c4f-7fd753f2a641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>9ff99ce4-68f6-4d01-894b-59cb59320946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormGrid&quot;)/table[1]/tbody[1]/tr[@class=&quot;hoverBackground&quot;]/td[@class=&quot;t-last&quot;]/div[@class=&quot;settings-actions btn-group button-positioning open&quot;]/ul[@class=&quot;dropdown-menu ul-setting&quot;]/li[6]/a[@class=&quot;small-x&quot;]</value>
      <webElementGuid>5ed3c75b-9ded-4e38-a0dd-08fdae8dd185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;TestForm('c0e9a917-c459-4fe4-9726-632b08e8b0ce', false);&quot;]</value>
      <webElementGuid>8f26fa04-474e-404b-a460-b1af0d944a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormGrid']/table/tbody/tr[3]/td[7]/div/ul/li[6]/a</value>
      <webElementGuid>e8412ba1-2713-477d-88ed-315037089ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Test')])[3]</value>
      <webElementGuid>04a57659-d0cd-414f-ab94-c936aade2d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unpublish'])[3]/following::a[1]</value>
      <webElementGuid>ff3e0c31-95c2-485d-ae49-a14eae024b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename'])[3]/following::a[2]</value>
      <webElementGuid>31c16d47-01c2-472a-a21b-1e8462ed0375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Form HTML'])[3]/preceding::a[1]</value>
      <webElementGuid>6529fe14-5fee-41de-be02-6aae8d203ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Edit'])[3]/preceding::a[2]</value>
      <webElementGuid>64d16e60-b7bc-46ad-b8ee-52cf7d7b5b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[23]</value>
      <webElementGuid>a5912316-f333-48e7-8a38-d9a29f7caeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[7]/div/ul/li[6]/a</value>
      <webElementGuid>b949328d-0b69-4016-aad1-5707fe8749ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Test' or . = 'Test')]</value>
      <webElementGuid>263c0a30-5235-4cfb-8ebb-f93d5fbdc98a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
