<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0 (1)</name>
   <tag></tag>
   <elementGuidId>9bcfced5-0348-44f3-975f-24384e5b50d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>563b951e-e199-4c45-8f26-77fcffd24bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block </value>
      <webElementGuid>39170404-0ba1-46f3-b3ac-b5ddb1a75680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-control-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bceb35fc-807c-44d8-8ca6-1e4e12cb6270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>889554f9-af3f-4cd9-bb05-4564edcbc710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>71c917de-df34-4ba0-a3df-0000ed119aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>9e0235fd-6e29-4b3a-bb1e-1fbc53f882ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>dc47eec4-010c-4260-b2b9-bdfe27d4d82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5bb43e30-f9f0-4f9f-8e18-c71987056a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>0cb6b4a4-e57c-4a39-ae77-ae1a50f48ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d26a7e8-0252-4b62-b525-bd2e2d2c06a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0&quot;)</value>
      <webElementGuid>e8eb36d7-0edc-465e-98af-da36642d5db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_9ae9be</value>
      <webElementGuid>7cd10e05-eea8-46fa-b358-0ecb162150ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0']</value>
      <webElementGuid>e5768841-9335-4614-9617-2feb814de723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__FirstName__Lead__0']/div/span[2]/input</value>
      <webElementGuid>bf6f56c7-0438-4f23-8551-b903d978a24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>0b096a3e-afac-480e-90d2-a04ddf842a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0' and @name = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0' and @type = 'text']</value>
      <webElementGuid>42504487-2b6b-4c10-925f-b22d7b3234af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
