<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</name>
   <tag></tag>
   <elementGuidId>00f0e789-6b4f-45ba-9d78-9156ca370e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60f8ed0e-66dc-47fd-b420-4af34f6c16fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block </value>
      <webElementGuid>e4a7f1fd-ef6a-4737-9666-93c66ab6f4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-control-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a6d8604-fcd0-4c19-bbac-fac2ca4677f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>6a218804-7717-48b9-9af7-4ff2121c71c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ed09bb8-dbde-42ac-84b3-167090a10cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>fbe96470-4de2-4336-829c-4bc0e8bd1099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c98a3c0d-9eb4-4ea5-a837-02384ee91964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c1943bf3-4a1e-40c1-946d-23cf5df02cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>e9e48eef-a187-4f38-991a-b9399f28b43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9f3e788-7f59-4d50-978a-4c8e41f97849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0&quot;)</value>
      <webElementGuid>db2ce332-6812-4589-b980-b45b86dee58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_b2aa29</value>
      <webElementGuid>3ef91cc0-ce8e-4529-ae7b-96caeb95102b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0']</value>
      <webElementGuid>006e8fec-b1b9-4786-8085-d33bca840851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__FirstName__Lead__0']/div/span[2]/input</value>
      <webElementGuid>6fd929a1-d5ae-40e7-ae41-3e649d91e9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>22dc85a2-ea41-42a3-ac03-97d2b20f9961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0' and @name = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0' and @type = 'text']</value>
      <webElementGuid>b7071ece-bf6d-4486-bdd7-ae9f85aabd25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
