<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X</name>
   <tag></tag>
   <elementGuidId>515a2672-5307-4ba9-9c13-9d0b6b276c82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_22mx_CustomObject_7__Activity__201']/div/span[2]/span/div/div[2]/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2.select2-container.select2-container--default.select-option-load-progress.select2-container--below.select2-container--open > span.selection > span.select2-selection.select2-selection--single</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d53de932-2873-4e21-916c-2fd3e0b6d268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single</value>
      <webElementGuid>59952af4-3184-4683-9d9d-62929d04121c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3b66926f-925f-45e6-8ae0-2cd4c6564d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>931b939b-fe78-427a-854c-fb31ce12fef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e60dc38-ba20-4802-9d34-d8788c265dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>676c8fcc-db37-4aec-80e0-7500b34c258d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b8dee057-71f9-480e-b38e-d97b34947dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container</value>
      <webElementGuid>03d0d734-fa28-4ec5-a45a-d70316294739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-results</value>
      <webElementGuid>8a7bb571-b9b1-4611-b447-721b845c2d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>3b002a21-e572-476d-901c-27a6d8dbaf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_22mx_CustomObject_7__Activity__201&quot;)/div[@class=&quot;form-group mx-custom-textfield mx-custom lsq-form-field-form-group  lsq-form-label-top      mx-custom-textfield-floating-label-hover-active&quot;]/span[@class=&quot;lsq-form-ctrl-field-container-block&quot;]/span[@class=&quot;lsq-form-ctrl-field-container-block lsq-form-ctrl-field-select2-container-block&quot;]/div[@class=&quot;lsq-form-select2-control-contianer&quot;]/div[@class=&quot;lsq-form-select2-control-wrapper&quot;]/span[@class=&quot;select2 select2-container select2-container--default select-option-load-progress select2-container--below select2-container--open&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]</value>
      <webElementGuid>38fbef2d-2b69-4349-983f-ba7b3a6dada9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_b2aa29</value>
      <webElementGuid>ebeea754-d648-4beb-826c-96fea1b576cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_22mx_CustomObject_7__Activity__201']/div/span[2]/span/div/div[2]/span/span/span</value>
      <webElementGuid>7f6612d6-bc89-4704-b192-befec0cace32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[47]/following::span[5]</value>
      <webElementGuid>e9fe681e-9bca-4dd8-8155-856cb9a0fd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CFS2 - Dropdown7'])[1]/following::span[6]</value>
      <webElementGuid>315446eb-23a4-43a8-8513-d63b43f64e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CFS2 - Dropdown8'])[1]/preceding::span[12]</value>
      <webElementGuid>8c36b20e-a321-4396-8f4a-a252b7c47f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/span[2]/span/div/div[2]/span/span/span</value>
      <webElementGuid>0c33794e-0e9c-4d84-a101-97001c61dae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'X' or . = 'X')]</value>
      <webElementGuid>d14415e3-bb8e-4d28-8743-db8df54b78d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
