<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_555</name>
   <tag></tag>
   <elementGuidId>b3c5a16c-7585-4097-877c-531084de15e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d165ff72-675d-41cb-96aa-12442879e3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>99d64741-4e0b-4f7e-a5de-9cd8c54f27f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container</value>
      <webElementGuid>8701e71d-9208-42ab-80b2-525f400bf8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>dac8d5b0-96af-49e7-b2d9-43d0039d5c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d46ebdbc-840c-45f3-9c95-28615cd78206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>555</value>
      <webElementGuid>346d781f-662b-4ac4-ab79-5f5870bbd7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>555</value>
      <webElementGuid>64ac7a34-5ce1-41ac-93a5-a4ba0b30a22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container&quot;)</value>
      <webElementGuid>fabd0111-5cfb-4a3f-87df-da60c26fdb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_9ae9be</value>
      <webElementGuid>57e8107e-8f88-41f5-9783-3a0be55f8f25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container']</value>
      <webElementGuid>167f96a2-71d9-48b3-8aa7-2e7f3acf14e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_22mx_CustomObject_7__Activity__201']/div/span[2]/span/div/div[2]/span/span/span/span</value>
      <webElementGuid>ffb437e0-2091-4ff8-8f5c-ef132abcceb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[47]/following::span[6]</value>
      <webElementGuid>ce165825-8f57-4b50-bfd8-cc0f3ab16bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CFS2 - Dropdown7'])[1]/following::span[7]</value>
      <webElementGuid>30dd8f6a-567a-4be2-b013-76d29813c7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[18]/preceding::span[2]</value>
      <webElementGuid>3ff22b18-12cc-4061-a935-3bef5affe5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CFS2 - Dropdown8'])[1]/preceding::span[10]</value>
      <webElementGuid>78ddcf61-a9fb-477d-988b-47bd959423e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/span[2]/span/div/div[2]/span/span/span/span</value>
      <webElementGuid>4cfa5cda-a93c-4719-8a4b-2b2bdbd08061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container' and @title = '555' and (text() = '555' or . = '555')]</value>
      <webElementGuid>43b1d6bd-2937-43c7-a5e0-93731f667c92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
