<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_666</name>
   <tag></tag>
   <elementGuidId>d4c97bef-9d47-48e3-b384-d24681efefa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7e8b676-718b-4e3d-a22e-80e72cb49321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>99df559a-f37f-4b76-85ce-f7e46a0ceb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container</value>
      <webElementGuid>60056f92-1559-43ba-9841-de06917ee3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>69afc1b6-0619-44d5-bc38-a1d2c049ffaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02a17578-b916-41f7-a8b4-cd2acdcfe3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>666</value>
      <webElementGuid>d351e653-ae54-4c39-8ae9-3d5ed0354db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>666</value>
      <webElementGuid>c726f4ac-f2d5-4be5-af2a-db67596b8c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container&quot;)</value>
      <webElementGuid>81303a7a-745a-4ca2-bd30-97d1b8d6a298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form - End to end/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_9ae9be</value>
      <webElementGuid>1c2681bf-1d0c-43fb-8e8e-de851353fc55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container']</value>
      <webElementGuid>af95bdbb-9be0-4806-8804-6bfcb29b2bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_22mx_CustomObject_7__Activity__201']/div/span[2]/span/div/div[2]/span/span/span/span</value>
      <webElementGuid>2fa7b2b2-2b50-48b6-8ff0-e7a9eff5e432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[47]/following::span[6]</value>
      <webElementGuid>dc19cd5a-9ff1-4094-8bd5-2f6fcdf20e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CFS2 - Dropdown7'])[1]/following::span[7]</value>
      <webElementGuid>4628462e-d291-42c9-9636-b8ebe0366a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[18]/preceding::span[2]</value>
      <webElementGuid>6f98efc3-29b8-4ef6-b417-ef054193709b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CFS2 - Dropdown8'])[1]/preceding::span[10]</value>
      <webElementGuid>d65991d8-21a0-49e7-a4c6-abec3632fddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/span[2]/span/div/div[2]/span/span/span/span</value>
      <webElementGuid>7d2acfd3-a31d-4a7e-9e08-23908d41995a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab3__section4__mx_Custom_22mx_CustomObject_7__Activity__201-container' and @title = '666' and (text() = '666' or . = '666')]</value>
      <webElementGuid>2b10fa7e-f74d-4adb-bd78-71b996947227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
