<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test</name>
   <tag></tag>
   <elementGuidId>9d0f3811-4b0c-4e06-af57-8fe51d3884c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;TestForm('9deb642d-728c-4671-a6aa-83e68313187e', false);&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6265131-3a62-4e5b-b7fd-d000772a801b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small-x</value>
      <webElementGuid>78ba6646-0e45-4225-8809-05fea7e71876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>97ceda6e-da61-4d8f-9269-be09bdf23c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TestForm('9deb642d-728c-4671-a6aa-83e68313187e', false);</value>
      <webElementGuid>13a15981-581c-47e5-9974-795d5b112d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>149bea65-1955-4d4b-bb85-2fb43b8fc36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormGrid&quot;)/table[1]/tbody[1]/tr[@class=&quot;hoverBackground&quot;]/td[@class=&quot;t-last&quot;]/div[@class=&quot;settings-actions btn-group button-positioning open&quot;]/ul[@class=&quot;dropdown-menu ul-setting&quot;]/li[6]/a[@class=&quot;small-x&quot;]</value>
      <webElementGuid>484085a1-14bc-4a72-b555-b27203853d05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;TestForm('9deb642d-728c-4671-a6aa-83e68313187e', false);&quot;]</value>
      <webElementGuid>4c8bbd40-086f-493b-ba8f-a73787cc0bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormGrid']/table/tbody/tr/td[7]/div/ul/li[6]/a</value>
      <webElementGuid>558354b8-338c-457f-baa3-7e6c1a4fb891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Test')]</value>
      <webElementGuid>69a408c7-f433-4375-8c63-053293fc590e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unpublish'])[1]/following::a[1]</value>
      <webElementGuid>09f15585-5efe-4f6f-9583-67be88b6b43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename'])[1]/following::a[2]</value>
      <webElementGuid>989e8768-fc37-490d-aff2-b67e365e424b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Form HTML'])[1]/preceding::a[1]</value>
      <webElementGuid>ec2fd1bb-1777-4ccb-859f-8630bcbde449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Edit'])[1]/preceding::a[2]</value>
      <webElementGuid>af5dd94c-69d2-4dce-af4d-290bce6ea55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test']/parent::*</value>
      <webElementGuid>e806a801-e725-43d2-b632-ae11b29129b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[11]</value>
      <webElementGuid>a1b1282d-8314-42af-921c-723e6b78ebc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/ul/li[6]/a</value>
      <webElementGuid>27908682-e3fc-49c8-9638-a03ab47fe45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Test' or . = 'Test')]</value>
      <webElementGuid>cb6b8ec3-b231-472b-98f5-41e2366961f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
