<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_37d1ea</name>
   <tag></tag>
   <elementGuidId>02c44521-ee9c-48eb-8efb-ee850a3b8697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655615053916_9421</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='lsq-form-iframe-container_1655615053916_9421']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e1f7fb23-5e43-4105-8946-dac1d0ede337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>e03e5788-fdf7-474b-a3b2-ec5b00cab6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655615053916_9421</value>
      <webElementGuid>4ef831c3-2b88-4554-9b8d-cc8a676f7940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655615053916_9421</value>
      <webElementGuid>b587d085-73e7-4eab-ba09-520883f49796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655615053916_9421&quot;)</value>
      <webElementGuid>f5dd682b-8677-4a09-adb4-7b30f5f97803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655615053916_9421']</value>
      <webElementGuid>c9e1028c-f9d8-4963-8b98-09ad3d6adfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>12f79a7d-0e38-404e-84ac-037f9b377b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/iframe</value>
      <webElementGuid>d6fadf20-f78e-4256-aa95-de2295b4f69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655615053916_9421' and @name = 'lsq-form-iframe-container_1655615053916_9421']</value>
      <webElementGuid>c95c30c7-6349-4c9c-924a-06d201d07cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
