<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mx-custom form-control lsq-form-fiel_39aad4</name>
   <tag></tag>
   <elementGuidId>94d9633b-50c1-4904-bc64-7fba55fed8a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mx-custom.form-control.lsq-form-field-ctrl-text.width-95.display-inline-block.calender-icon.lsq-flatpickr-to-init.flatpickr-date-time.flatpickr-input.input.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e73fb70f-d345-4136-baf6-4e6713e44c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active</value>
      <webElementGuid>82609027-c96e-4576-ae8b-7ccd50a306f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d19a8db-5417-4b5a-93dc-fda7985f6cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edc92d0b-3840-407c-8ca3-c6ca7775ea39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>9f7526da-788d-4c70-b8f7-f4fbf1f14d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FF_9deb642d-728c-4671-a6aa-83e68313187e__mx_Custom_18mx_CustomObject_8__Activity__201&quot;)/div[@class=&quot;form-group mx-custom-textfield mx-custom lsq-form-field-form-group  lsq-form-label-top&quot;]/div[@class=&quot;lsq-form-datetimepicker-container lsq-form-ctrl-field-container-block lsq-form-flatpickr&quot;]/span[@class=&quot;lsq-form-date-time-picker&quot;]/span[1]/input[@class=&quot;mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active&quot;]</value>
      <webElementGuid>4ca591f2-29cc-4ac4-b305-981a1cddcd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form -create case with validation/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_37d1ea</value>
      <webElementGuid>80bf8fb0-caa9-4c5f-a1ae-11f7c1014e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>f955ed65-e7bd-47d8-8dec-4a761c6c17d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_9deb642d-728c-4671-a6aa-83e68313187e__mx_Custom_18mx_CustomObject_8__Activity__201']/div/div/span/span/input[2]</value>
      <webElementGuid>9cdec3a8-dedc-4e5b-b5bf-fc32f6e2aacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input[2]</value>
      <webElementGuid>9aece1ce-3c6a-4c06-9ac6-c6d7fde13be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>dd809f8a-c22d-4498-97f9-f12c20446544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
