<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</name>
   <tag></tag>
   <elementGuidId>0f99f682-950a-42a5-a827-c03e0cdb448f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0230d87d-d37e-4072-856b-ddec9ae9776a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block </value>
      <webElementGuid>9c33ac74-33a7-47e2-9595-997c640fe5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-control-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1f5376af-4d60-4f5b-8fa8-c1c682bb9cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>6ed71eba-5269-46ce-b001-ac6f0f13c9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0620d28-cf7f-4ae1-ab58-f1c5baf1b8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>d1a4b240-be0f-4d5b-bb16-7819a04921ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>9a439b20-8a66-4f06-9107-5e6866985403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>816db054-b8ad-4b28-8510-089d8e4ec1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>5dfb26ed-57f7-49db-9a76-93e4a703c333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d44513c5-b0e8-4c73-be8c-9266e4b11de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0&quot;)</value>
      <webElementGuid>347ca085-f9fe-4253-8115-37ae66f7b4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Form -create case with validation/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_37d1ea</value>
      <webElementGuid>2127fe28-b9cf-4425-8a73-31bf6b66975b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0']</value>
      <webElementGuid>6db7c52f-a504-4843-9b24-9fb768e8814f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_9deb642d-728c-4671-a6aa-83e68313187e__FirstName__Lead__0']/div/span[2]/input</value>
      <webElementGuid>2fcbbba0-26cf-484b-b150-ee7f0d3acf06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>8bc7f6da-08f5-4a8a-a6f5-6cc4af7cfa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0' and @name = '9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0' and @type = 'text']</value>
      <webElementGuid>3db1c1ee-1e18-43ea-bfad-7ca56e8fd179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
