<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1</name>
   <tag></tag>
   <elementGuidId>dcce9fa6-eda0-4edc-946e-fa338a7cac3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-primary.btn.lsq-signin-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce620bb5-9e00-4ad5-8a3a-c7e9c1bbb7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary btn lsq-signin-button</value>
      <webElementGuid>2af58256-7b9b-431b-840a-79820ed0d916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>verify-password</value>
      <webElementGuid>1a1ff20a-1325-4608-adb5-ec1e161151e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4a5bb2a-a9e9-4123-b8c6-c0c5c9e044d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>8d9c6cd0-d346-4789-bddf-6aaa26dbd16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-container&quot;)/div[@class=&quot;login-form-body&quot;]/div[@class=&quot;login-form-body-wrapper&quot;]/div[@class=&quot;login-form-body-container&quot;]/div[@class=&quot;lsq-sigin-verify-password&quot;]/div[@class=&quot;lsq-signin-footer&quot;]/button[@class=&quot;btn-primary btn lsq-signin-button&quot;]</value>
      <webElementGuid>15130f08-0087-41b7-9700-7368bc78070b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>312a0ad0-e0fc-446f-a934-f5dcb2a5cbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary btn lsq-signin-button</value>
      <webElementGuid>f97147b7-9cb2-4026-90e2-01ab0d214580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>verify-password</value>
      <webElementGuid>f79d8d23-5c3b-4990-bc88-4dc00394a948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8adc7ce1-ddcf-4c04-a3b5-ca85304c47f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>22fced5e-734b-4f8c-a6e7-7a06c8356d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-container&quot;)/div[@class=&quot;login-form-body&quot;]/div[@class=&quot;login-form-body-wrapper&quot;]/div[@class=&quot;login-form-body-container&quot;]/div[@class=&quot;lsq-sigin-verify-password&quot;]/div[@class=&quot;lsq-signin-footer&quot;]/button[@class=&quot;btn-primary btn lsq-signin-button&quot;]</value>
      <webElementGuid>cbab38d6-b6ad-41f2-a3cb-16cca5ed6623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>4456a6f5-3300-47bd-8f87-0a5a1fc5af40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form-container']/div[2]/div/div/div/div[3]/button</value>
      <webElementGuid>9411037f-69d0-49f8-a313-489bed639a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::button[1]</value>
      <webElementGuid>ae440515-2b62-40e8-bebc-755a81fa1188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your password'])[1]/following::button[1]</value>
      <webElementGuid>68f4c026-a116-4aed-8624-edd55fb3e43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© Copyright 2022, MarketXpander Services Pvt. Ltd. All rights reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>8551c7fd-df3d-4cdd-ba33-3a6530dce634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::button[1]</value>
      <webElementGuid>d5018b15-ff6f-43bd-b8f2-47d86d2dabe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>58375060-052f-4d1c-ac9d-d7aa9bc63660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>da824cea-a18a-4d39-9482-289d12763c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>696e8b6f-37f5-415e-b6c9-7b969a32c275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
