<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_00d483</name>
   <tag></tag>
   <elementGuidId>b809f3ee-8eb2-46f7-8174-f51ae67bc954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='lsq-form-iframe-container_1655551913344_2565']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655551913344_2565</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>aeb9b241-ecc0-4aa1-9da1-f1791c559a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>89555eab-6b5a-43fa-b685-56b7b1747d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655551913344_2565</value>
      <webElementGuid>cf85b152-8369-4393-9a6f-289e20ce36dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655551913344_2565</value>
      <webElementGuid>c416546a-ca68-4952-abf3-7b87733730a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655551913344_2565&quot;)</value>
      <webElementGuid>8f6513ac-daf0-478c-bb7a-cd4331a0bea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655551913344_2565']</value>
      <webElementGuid>69fe555b-df72-48f1-8b21-769ab19cc4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>5b04f1e1-9021-4aa0-af1e-8e5f4c3ec9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/iframe</value>
      <webElementGuid>8b5bf7b9-1e8a-4d1c-9a0c-f9304bf2c1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655551913344_2565' and @name = 'lsq-form-iframe-container_1655551913344_2565']</value>
      <webElementGuid>4c4da6f6-8582-4f2a-aa33-ad8bc64b18e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
