<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201</name>
   <tag></tag>
   <elementGuidId>be5e169e-f89d-4a89-bb0b-d623fddc595c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>218ad3be-a375-4c20-8a35-4e177087f21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block lsq-form-field-control-initialize  lsq-form-number-spinner entity-numeric-field</value>
      <webElementGuid>b530e843-6989-4c50-ba2a-77333c32a72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201</value>
      <webElementGuid>c96e1beb-d65f-4f84-977e-bff8b5129e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201</value>
      <webElementGuid>d1e45d72-2ee7-4df0-87e5-2d3a0d74ecf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>mx_CustomObject_4</value>
      <webElementGuid>be8d92e1-b2bd-40ee-bd92-a862fd93abae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Value</value>
      <webElementGuid>dbd37669-d9c0-4be3-8368-a0b33e34ad3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-readonly</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2267c088-7086-430e-b4f5-a0eee7d14ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>-2147483648</value>
      <webElementGuid>28316cf4-9035-4ffc-8f0d-20f10c4f4de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>fbd6bbd5-b494-4059-99ee-fda5538f13cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>-2147483648</value>
      <webElementGuid>2ff42dbc-e770-4e3a-89e3-332109c67e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>eb9746a8-7d64-4898-88e1-b9da1456f082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>f6a381b3-fe6e-46f9-ac31-8f32405a8c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201&quot;)</value>
      <webElementGuid>736854b0-3d8f-4d63-8e06-c3b2a34e9160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RS4 - validation/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_00d483</value>
      <webElementGuid>b4924add-0cb6-491f-9f14-37beffdf0595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201']</value>
      <webElementGuid>c3191aa8-26c0-4977-96c4-71d32367de5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_18mx_CustomObject_4__Activity__201']/div/span[2]/div/input</value>
      <webElementGuid>b472695f-53b8-475b-b627-790087fd2d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span[2]/div/input</value>
      <webElementGuid>ef03bc7c-a8cd-48c6-adb2-0ae6b1f9f941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201' and @name = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_4__Activity__201' and @placeholder = 'Enter Value']</value>
      <webElementGuid>fb327f06-4a12-4df2-a09c-5ffba742cae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
