<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_808d2d</name>
   <tag></tag>
   <elementGuidId>7f4ae3eb-8ab4-4a6a-af53-2f117e424894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lsq-form-modal']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655537685996_7612</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>44ce4bc2-e36d-410d-894d-442fac0aa38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>c49886a5-02d3-4f79-a373-ada1497a6e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655537685996_7612</value>
      <webElementGuid>46b64c14-104f-4090-8beb-914105b9dc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655537685996_7612</value>
      <webElementGuid>5d6bb323-908b-4337-a542-d587f76f591f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655537685996_7612&quot;)</value>
      <webElementGuid>41d8d482-50ad-442e-a62b-eec2c563eb70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655537685996_7612']</value>
      <webElementGuid>f0c4cf95-4a62-437a-b401-86c1df80b216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>a8bb7679-cd62-4d7b-bc3d-8a91b8259f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/iframe</value>
      <webElementGuid>a643ef44-9d9d-4ba1-932c-978f6ab1a07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655537685996_7612' and @name = 'lsq-form-iframe-container_1655537685996_7612']</value>
      <webElementGuid>2154a61c-1ed2-4ae5-b01b-cebfdea40677</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
