<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_da0e23</name>
   <tag></tag>
   <elementGuidId>183ea74a-8894-4bd6-a032-fc2d19f2364e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lsq-form-modal']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655536773541_6860</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a62dc047-30f8-4793-85d9-d9cc49aa2d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>064dc5f3-5503-4d7c-98fd-3ad75dc236c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655536773541_6860</value>
      <webElementGuid>a7a305c3-3c76-48e1-af3f-b7363841e613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655536773541_6860</value>
      <webElementGuid>bc1b2063-1617-4118-9ac7-1d075d7cac3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655536773541_6860&quot;)</value>
      <webElementGuid>39f50b84-43dc-4d33-b200-8c895d107825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655536773541_6860']</value>
      <webElementGuid>9b1bdcba-24be-4bfa-b468-aded12601116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>229e4578-a498-4683-bd69-e3ee304c51b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/iframe</value>
      <webElementGuid>651cf112-2bbd-41f2-aed5-c3b23b428aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655536773541_6860' and @name = 'lsq-form-iframe-container_1655536773541_6860']</value>
      <webElementGuid>1b5da547-2feb-4c90-818e-f8478ac13268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
