<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</name>
   <tag></tag>
   <elementGuidId>2c5b4c69-cdf8-495e-aaa9-842ef7dac5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf2dc98f-f803-46b0-be98-b01441b18789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block </value>
      <webElementGuid>4ef5f12b-598a-4414-a77f-d4205308bde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-control-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b190af4e-a646-4675-9537-b1e9a1e89a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>840fb747-9dbc-413e-8a09-c6951bcb1573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09937705-f059-4210-a806-22be3b70aebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>50e7cace-a087-44e1-aa2b-4bad9695fc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>765dcf6e-761a-4153-9746-c222e99c8f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6c01674e-a475-4a17-bf10-4ea7f29901b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>33e3e30a-9b7b-4883-b4b8-c86f4460dc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e485078e-01f8-4528-91ea-afd4ba32a160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0&quot;)</value>
      <webElementGuid>d5b4e8c9-e58a-41d4-99d2-eac481dfb5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RS4/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_da0e23</value>
      <webElementGuid>93e0cd36-319f-4893-a75d-f9d1412af56e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0']</value>
      <webElementGuid>a5ca0d62-75ad-4962-891c-ab0747cd6f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__FirstName__Lead__0']/div/span[2]/input</value>
      <webElementGuid>a22749e9-1bc9-4029-bc33-bc9203be9ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>89092ebe-5ff3-42fd-9997-092f9a742d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0' and @name = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0' and @type = 'text']</value>
      <webElementGuid>c6d80387-300f-468e-96e9-45a6b17c460b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
