<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mx-custom form-control lsq-form-fiel_39aad4 (1)</name>
   <tag></tag>
   <elementGuidId>d8272e76-4eb3-4049-840b-7356dba2fdd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mx-custom.form-control.lsq-form-field-ctrl-text.width-95.display-inline-block.calender-icon.lsq-flatpickr-to-init.flatpickr-date-time.flatpickr-input.input.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3b10b85-2333-49ca-88e2-7b4a88a6abb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active</value>
      <webElementGuid>1dd51da1-96a5-40aa-b4b2-2c36ccfddbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e456cc3d-a1c5-46a5-9c4c-28bcf573fde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5aaa6379-036f-4900-a7c4-c403136bdb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>956fb026-fb37-4bef-abbf-f1cc99bea5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_18mx_CustomObject_8__Activity__201&quot;)/div[@class=&quot;form-group mx-custom-textfield mx-custom lsq-form-field-form-group  lsq-form-label-top&quot;]/div[@class=&quot;lsq-form-datetimepicker-container lsq-form-ctrl-field-container-block lsq-form-flatpickr&quot;]/span[@class=&quot;lsq-form-date-time-picker&quot;]/span[1]/input[@class=&quot;mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active&quot;]</value>
      <webElementGuid>691e8b26-f76a-49a1-88e1-ac50b3ac07db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RS4/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_922b9a</value>
      <webElementGuid>5898741a-86d0-416a-8e6e-d6a2470d0d79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>669d535b-be69-4813-9096-0c7132f514ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_18mx_CustomObject_8__Activity__201']/div/div/span/span/input[2]</value>
      <webElementGuid>dc6d6173-3f8d-40ae-b419-9b321f0498b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input[2]</value>
      <webElementGuid>1c62c9bd-7304-468f-9edb-92074819fe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>cda5877f-c668-4f42-84f6-26c625c93329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
