<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mx-custom form-control lsq-form-fiel_39aad4 (3)</name>
   <tag></tag>
   <elementGuidId>7e692796-20a7-4cda-846e-16f389d7df1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mx-custom.form-control.lsq-form-field-ctrl-text.width-95.display-inline-block.calender-icon.lsq-flatpickr-to-init.flatpickr-date-time.flatpickr-input.input.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e565f1e-f09f-46b4-9c0e-b9ec6ddc0f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active</value>
      <webElementGuid>dbdf56de-3801-48ad-9feb-4a5892339a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e925e112-ffa5-41b4-a03a-e0b270a12062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f5a284b-44d7-483b-b619-1774cd452dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>45473f09-3702-475f-8062-055d5b26c6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_18mx_CustomObject_8__Activity__201&quot;)/div[@class=&quot;form-group mx-custom-textfield mx-custom lsq-form-field-form-group  lsq-form-label-top&quot;]/div[@class=&quot;lsq-form-datetimepicker-container lsq-form-ctrl-field-container-block lsq-form-flatpickr&quot;]/span[@class=&quot;lsq-form-date-time-picker&quot;]/span[1]/input[@class=&quot;mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active&quot;]</value>
      <webElementGuid>8ab7b669-3ed3-4a16-9b31-65750c78e010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RS4/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_da0e23</value>
      <webElementGuid>a1b178a3-89a0-47da-8cf2-7ec90d83feae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>1b5e9bab-f9fa-4c90-90a5-1e27b4b904a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_18mx_CustomObject_8__Activity__201']/div/div/span/span/input[2]</value>
      <webElementGuid>bfdc50fc-fae5-44f8-8857-cc23d19eb17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input[2]</value>
      <webElementGuid>09f42ab1-d269-4731-b30c-5c34a84265ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>f9e55fe7-804b-479e-b621-bef4c0cde7b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
