<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mx-custom form-control lsq-form-fiel_39aad4 (2)</name>
   <tag></tag>
   <elementGuidId>9fa83497-93cf-4c5b-8d71-7403ef5ad255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mx-custom.form-control.lsq-form-field-ctrl-text.width-95.display-inline-block.calender-icon.lsq-flatpickr-to-init.flatpickr-date-time.flatpickr-input.input.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3265b52-cfb3-4ec9-b6f9-38c6d3f96d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active</value>
      <webElementGuid>f6f77354-c2aa-4373-b40f-891d8d5881fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c3f9f2da-07ee-433c-90f9-1aeec7819e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d03d536f-8ec1-4e86-b340-483da1ba2121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>9a31aa83-3017-40f6-8949-20cc4df6f711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_18mx_CustomObject_8__Activity__201&quot;)/div[@class=&quot;form-group mx-custom-textfield mx-custom lsq-form-field-form-group  lsq-form-label-top&quot;]/div[@class=&quot;lsq-form-datetimepicker-container lsq-form-ctrl-field-container-block lsq-form-flatpickr&quot;]/span[@class=&quot;lsq-form-date-time-picker&quot;]/span[1]/input[@class=&quot;mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active&quot;]</value>
      <webElementGuid>2725aa06-fe02-4d07-8d06-ad18df79978d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RS4/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_7227a6</value>
      <webElementGuid>f0069d6a-6d68-4b3d-99a4-404eaa0c8f27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>069a3209-7e12-4a14-a4fd-53a7df4fccde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_18mx_CustomObject_8__Activity__201']/div/div/span/span/input[2]</value>
      <webElementGuid>7a2bd41c-39d5-451f-b7c3-3b58c9e78f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input[2]</value>
      <webElementGuid>9ccb06e0-3cf5-4162-893d-720164197ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>c9d6d822-a2f5-4c9e-a5ee-3cb7a967f999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
