<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Publish</name>
   <tag></tag>
   <elementGuidId>a2d9883c-dc16-4c83-a025-2350b6b99ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lsq-form-builder-tool-publish-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-builder-tool-publish-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2eb912f9-a690-414e-8679-127e435225af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary btn</value>
      <webElementGuid>412dc78e-4029-4b3d-8073-782ceb3c208b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_operation</name>
      <type>Main</type>
      <value>publish</value>
      <webElementGuid>16028c3d-59fb-4b3b-b490-a73cd3e357c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-builder-tool-publish-btn</value>
      <webElementGuid>317d5e01-ea20-4f72-8723-217c3aa5f414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-builder-tool-publish-btn</value>
      <webElementGuid>7ea64835-4fa3-4c48-9800-611155ac51a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3cb21a1c-2a80-4f22-aa6c-f5f7cc7e7984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publish</value>
      <webElementGuid>c699a0e4-89f8-418f-b7ee-110e09c4de9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-builder-tool-publish-btn&quot;)</value>
      <webElementGuid>03154529-7150-47f2-9fb2-5933705da915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='lsq-form-builder-tool-publish-btn']</value>
      <webElementGuid>35c40a12-8468-4c4b-8a33-f4348b75b00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mx-site-main-body']/div[2]/div/div/div/ul/li[7]/button</value>
      <webElementGuid>170bf143-b144-46ae-8933-f058ea68f8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Modified'])[1]/following::button[1]</value>
      <webElementGuid>86c6a308-e9df-464c-aca3-4d74ae7f2627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shwetha'])[2]/following::button[1]</value>
      <webElementGuid>1b3335ed-938e-4ed6-b462-b7f170dc21d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save as Draft'])[1]/preceding::button[1]</value>
      <webElementGuid>1e3b4c25-089f-4055-bce3-43bff3786d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publish']/parent::*</value>
      <webElementGuid>a2dd1fa8-311c-4d5d-9602-451ef213863c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f1c08569-9b22-42f2-b802-36f63c11076a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'lsq-form-builder-tool-publish-btn' and @name = 'lsq-form-builder-tool-publish-btn' and @type = 'button' and (text() = 'Publish' or . = 'Publish')]</value>
      <webElementGuid>476ce2e5-68c2-45fe-870c-fe1ed764b8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
