<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Form Name_lsq-form-builder-prop-name</name>
   <tag></tag>
   <elementGuidId>23f40f14-8c02-4122-a49e-2558f02a6f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lsq-form-builder-prop-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-builder-prop-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acfca79a-a3ce-4036-9dbe-d1dc47c48715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-builder-form-name lsq-form-builder-prop-name</value>
      <webElementGuid>e21c7683-8b76-48ce-b021-b91fd3940051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>Form 7</value>
      <webElementGuid>87030997-af0d-42c7-a855-2972ad093b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-builder-prop-name</value>
      <webElementGuid>ffd9d381-8a92-4b53-9094-5f8a812a3aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b56ab80d-2108-491b-bdc6-ed72caec8997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-builder-prop-name</value>
      <webElementGuid>2aec162a-60e3-4940-ad20-db4eebcfb0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43fa40f0-c218-4ff5-807d-094f6bc35ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Form 7</value>
      <webElementGuid>62ddfd90-5ce2-4cb0-b583-95c4ef04ccf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-builder-prop-name&quot;)</value>
      <webElementGuid>bb1c6ab6-7d4c-4a7f-a083-75a1cff477cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lsq-form-builder-prop-name']</value>
      <webElementGuid>4142de5a-4a8d-4351-8c7f-7cbfcd18041f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-builder-prop-step1']/div/div[2]/div/input</value>
      <webElementGuid>30fb5e7b-359d-4ceb-aac2-2674c814b4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>78c158ff-e5ef-461e-a7de-6fa0c1a8c8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lsq-form-builder-prop-name' and @name = 'lsq-form-builder-prop-name' and @type = 'text']</value>
      <webElementGuid>e6f6e797-7c58-4a7f-9176-668407690187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
