<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test</name>
   <tag></tag>
   <elementGuidId>23e6f905-40e1-4cd0-a997-29fdc93a1d0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;TestForm('c0e9a917-c459-4fe4-9726-632b08e8b0ce', false);&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f696a93-d06d-4723-b269-627cf208a2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small-x</value>
      <webElementGuid>32e2b3c6-692f-40c4-b26f-7b7b96474d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>31e1c749-d84d-4b81-91dc-6da71adb9b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TestForm('c0e9a917-c459-4fe4-9726-632b08e8b0ce', false);</value>
      <webElementGuid>79a68f0f-82d5-45ca-b3b9-403758973d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>69e19579-e69f-4da3-b06e-7617aa5791ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormGrid&quot;)/table[1]/tbody[1]/tr[@class=&quot;hoverBackground&quot;]/td[@class=&quot;t-last&quot;]/div[@class=&quot;settings-actions btn-group button-positioning open&quot;]/ul[@class=&quot;dropdown-menu ul-setting&quot;]/li[6]/a[@class=&quot;small-x&quot;]</value>
      <webElementGuid>7231d2c9-d3be-433b-a32d-813826df978e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dfb40ed4-1bfe-49f0-8aeb-1bc8d0a399a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small-x</value>
      <webElementGuid>b0c9a867-6481-49f5-aaad-c9c73470498d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>1d90a564-60cd-4064-bf80-9e7bc7182ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TestForm('c0e9a917-c459-4fe4-9726-632b08e8b0ce', false);</value>
      <webElementGuid>4dd61ce3-0610-4608-885d-58a432aebaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>85048c9b-5703-40df-a222-913ce2515b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormGrid&quot;)/table[1]/tbody[1]/tr[@class=&quot;hoverBackground&quot;]/td[@class=&quot;t-last&quot;]/div[@class=&quot;settings-actions btn-group button-positioning open&quot;]/ul[@class=&quot;dropdown-menu ul-setting&quot;]/li[6]/a[@class=&quot;small-x&quot;]</value>
      <webElementGuid>472efd0c-7024-48b6-ab15-3a6cf111c61e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;TestForm('c0e9a917-c459-4fe4-9726-632b08e8b0ce', false);&quot;]</value>
      <webElementGuid>c0d708c1-a0bb-450b-ac78-dc4253917c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormGrid']/table/tbody/tr[3]/td[7]/div/ul/li[6]/a</value>
      <webElementGuid>cca1d4fb-baa9-486e-98d4-211640472ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Test')])[3]</value>
      <webElementGuid>0a96db94-cda9-4860-95e0-7ab4d91fb0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unpublish'])[3]/following::a[1]</value>
      <webElementGuid>01e93fc7-c25c-4d93-a2ec-3a98997f19b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename'])[3]/following::a[2]</value>
      <webElementGuid>cce23643-edc1-4031-ade5-ac3d1dbb415c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Form HTML'])[3]/preceding::a[1]</value>
      <webElementGuid>9735d11c-a99f-42f3-a242-e6e9e76f4c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Edit'])[3]/preceding::a[2]</value>
      <webElementGuid>1a50593d-d879-4f4e-b46d-83d777ea4982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[23]</value>
      <webElementGuid>db5955dc-46fe-4264-b5c4-36441d1589d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[7]/div/ul/li[6]/a</value>
      <webElementGuid>5b44404c-68f6-4133-8637-ac9aa4f0b37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Test' or . = 'Test')]</value>
      <webElementGuid>ebfee132-dc5c-45c7-9c9d-c116668ac969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
