<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_24bdd5</name>
   <tag></tag>
   <elementGuidId>6b4a2687-4074-4e3a-a3ba-35d455d65de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lsq-form-modal']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655546209455_5282</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>60b1dddc-a414-4d57-8218-2722838b7b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>eaae72b1-274f-43d9-9b18-aeef64ad3211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655546209455_5282</value>
      <webElementGuid>62068845-b896-42f2-bf83-5d33c993eba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655546209455_5282</value>
      <webElementGuid>445a225c-cf35-4d17-83a9-be3f02851537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655546209455_5282&quot;)</value>
      <webElementGuid>adb99970-f984-4c01-84ee-25bc095a83c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655546209455_5282']</value>
      <webElementGuid>54278933-1a38-4371-b811-ce3c3d3f932b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>fdb98e39-bf6a-4575-a489-ba46a837429c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/iframe</value>
      <webElementGuid>7b6c1e1a-1367-48ae-9ee3-1d218c8c987a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655546209455_5282' and @name = 'lsq-form-iframe-container_1655546209455_5282']</value>
      <webElementGuid>bde37708-0c9b-45dd-9887-2a49308627dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
