<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0 (1)</name>
   <tag></tag>
   <elementGuidId>164591ed-c4ce-4cdc-a1c8-a347b976d88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f884c4d-21ff-42f4-9c8a-e793b60c5453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block </value>
      <webElementGuid>e140633f-edf1-4942-92b6-bb952c4931c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-control-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1be6954-d2ff-4b7d-969e-e7d8fb09cc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>6a945757-50c5-4031-92e2-6312001bae03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3538c5de-8ef4-4198-9d83-6fccb466b48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>96ab5a62-2b51-4ce9-9ada-84bfdb3f2407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e06c07ee-1acb-4093-ab52-cf2d6c31918c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b9472039-4466-4320-9291-a76be3f39f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>b119f30c-f177-436a-8612-8034a9c9b800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>518bccb9-d9f9-4d94-bb0b-aab48a5c799d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0&quot;)</value>
      <webElementGuid>9460b9d7-865b-46cf-9e2f-7bb3f1d8205d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/get value of an object/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_24bdd5</value>
      <webElementGuid>0f9db2f4-3b8f-4990-865a-bc4f5150dd54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0']</value>
      <webElementGuid>d27d6b0e-ba0e-46b9-9988-15e379ed784d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__FirstName__Lead__0']/div/span[2]/input</value>
      <webElementGuid>135f1bbc-5f37-40e7-b579-0b1f577a8975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>88909558-a599-47de-95a4-48195273b900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0' and @name = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section1__FirstName__Lead__0' and @type = 'text']</value>
      <webElementGuid>e5154662-4ea0-4d2e-af68-cc159eae5dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
