<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__c0e9a917-c459-4fe4-9726-632b08e8b0ce_2cc1e9</name>
   <tag></tag>
   <elementGuidId>7fdc9584-5c42-4157-ad9e-1bdb324de4fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_2__Activity__201']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_2__Activity__201</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a81641da-06f0-4c6f-8803-a397fef39a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block lsq-form-field-control-initialize  lsq-form-number-spinner entity-numeric-field</value>
      <webElementGuid>b5c44bb6-ed57-43b1-8a4d-db77792bc555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_2__Activity__201</value>
      <webElementGuid>ca20e2af-a56b-4856-b67c-c935086ec770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_2__Activity__201</value>
      <webElementGuid>5fa9c8de-7ba1-4e58-8b51-de61a52c2689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>mx_CustomObject_2</value>
      <webElementGuid>0080938e-1515-4fd1-8fff-0c2a46d3640f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Value</value>
      <webElementGuid>e2bc3fd5-e8cf-47e4-9f2b-dd0bf175126c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-readonly</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ca9a6155-45fe-490e-bdf4-da68216564e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>-2147483648</value>
      <webElementGuid>ca6b79c2-7f5f-4d00-9433-42992d889165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>29fbd111-b2f1-4e27-8695-6c26fb8cdea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>-2147483648</value>
      <webElementGuid>b6fe8f15-c3be-42cc-846b-8db625443097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>1dddc730-4ac1-4fff-8cf2-bb0259ffc234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>1ecd3ac7-f115-4e1e-ad3c-21c31977319a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_2__Activity__201&quot;)</value>
      <webElementGuid>0078ddbc-2eb2-48ac-9db5-5274423cf80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/get value of an object/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_c61d5d</value>
      <webElementGuid>d6bfdeaa-2984-4445-afc2-902657c1f492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_2__Activity__201']</value>
      <webElementGuid>9ace4f0c-c6db-4e05-a720-903a10d27fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_c0e9a917-c459-4fe4-9726-632b08e8b0ce__mx_Custom_18mx_CustomObject_2__Activity__201']/div/span[2]/div/input</value>
      <webElementGuid>65f18cc3-e5fc-439b-b413-01eac8cbbbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span[2]/div/input</value>
      <webElementGuid>f0106e00-f8b4-49c7-b20c-dabed93df192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_2__Activity__201' and @name = 'c0e9a917-c459-4fe4-9726-632b08e8b0ce__tab1__section2__mx_Custom_18mx_CustomObject_2__Activity__201' and @placeholder = 'Enter Value']</value>
      <webElementGuid>164e929e-4024-4bf1-89ab-238ebf6a1158</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
