<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your login details_EmailID</name>
   <tag></tag>
   <elementGuidId>2deb19d0-da2b-4df7-b60b-3e06a9299f60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EmailID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1d72ecc-396b-4cad-8c28-8e32f22cb545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>ced0cf38-1a89-4e60-a118-f23d81f7fd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6635a342-8df3-4e21-98ed-707f673bd3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Enter a valid email address</value>
      <webElementGuid>a280c89c-d395-4b0a-b193-269b6019d557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\s*((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.+]?[a-zA-Z0-9])*))[@]((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.]?[a-zA-Z0-9])*))[\.][a-zA-Z]{2,}\s*$</value>
      <webElementGuid>e7e68867-875f-4203-97d2-aa40f6069d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Email address is required</value>
      <webElementGuid>59dd1314-d5d5-4eaf-b27d-969b6e277adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>9bc1f5b5-3938-4953-8d97-e3562fd89cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>52806502-d8de-4d8d-bde9-944abbea2a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>c65b796b-2847-4eee-a628-ff94895b0e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>4297df96-8e25-40cb-a7d8-fce06d8d01d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff7d7ec7-903a-4bbf-b187-a92c3b63d8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailID&quot;)</value>
      <webElementGuid>ea9a7d54-c2f8-4f85-8f4e-acd9f46ecd78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailID']</value>
      <webElementGuid>c09ceab9-f63c-41e3-a6ab-b0a99d9e3721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='VerifyEmailForm']/input</value>
      <webElementGuid>4fa464bf-d2f6-43cd-a4a3-4ff603a01a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3d6831ae-4335-4a46-9328-9f49e02ef3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailID' and @name = 'EmailID' and @placeholder = 'Email address' and @type = 'text']</value>
      <webElementGuid>1346da50-74a7-4a7a-8fd9-b85124d4ded9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
