<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_3a81c7</name>
   <tag></tag>
   <elementGuidId>5449072c-dc4e-4e3d-88f0-7b4adb3b4477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655636763614_0031</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lsq-form-modal']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f1bb4cbd-04f4-4ab1-94d9-6eeb0b22bfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>ed72579c-08c3-4ab0-bf87-06f4c159d5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655636763614_0031</value>
      <webElementGuid>6be8b981-a62f-4463-91a7-f67f8b1ae08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655636763614_0031</value>
      <webElementGuid>4c80f790-72f5-4157-9203-2b042aa23832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655636763614_0031&quot;)</value>
      <webElementGuid>54b0f422-1737-4ae5-a95c-be9bcdb49950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655636763614_0031']</value>
      <webElementGuid>d33ca1cc-443d-4716-af95-0db4f43516e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>82456fde-d4c1-40d9-97c2-a7c9252728e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/iframe</value>
      <webElementGuid>0ad7bf20-0b14-4d64-ad6f-9f0c7d4529e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655636763614_0031' and @name = 'lsq-form-iframe-container_1655636763614_0031']</value>
      <webElementGuid>799cc499-d6ef-4712-a756-55de7536765b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
