<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_742ad8</name>
   <tag></tag>
   <elementGuidId>a8bc2870-fffb-4417-acb6-8e5895e3caed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655624073661_2111</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='lsq-form-iframe-container_1655624073661_2111']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>00827176-83f9-4566-b485-533b1c7f6a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>207ef5c4-49ef-4e68-9580-d565d72fb704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655624073661_2111</value>
      <webElementGuid>8b07cb03-7ced-4f1e-8ff4-bdf368cf3edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655624073661_2111</value>
      <webElementGuid>7a76474f-07bc-4120-b4a4-9a8d940048d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655624073661_2111&quot;)</value>
      <webElementGuid>87f19b87-a4c7-4440-97cb-2dec15987eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655624073661_2111']</value>
      <webElementGuid>b770d479-d598-482d-a0ef-b54f6f813b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>6933b72a-10e9-48df-977d-2a224768a103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/iframe</value>
      <webElementGuid>1055c80c-3d3c-4a3b-b395-284a396f90c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655624073661_2111' and @name = 'lsq-form-iframe-container_1655624073661_2111']</value>
      <webElementGuid>a35dceb3-800f-4d68-898e-4cb3615743a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
