<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_dfdaf8</name>
   <tag></tag>
   <elementGuidId>80b153c4-60bb-483b-847e-119edfe697ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655639642846_0162</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='lsq-form-iframe-container_1655639642846_0162']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e4637b28-f332-4a4e-a023-4ee5533debca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>b6631829-a537-4f05-9f57-a20b33c857b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655639642846_0162</value>
      <webElementGuid>8beb0919-03d6-4fde-8565-11113bd085d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655639642846_0162</value>
      <webElementGuid>387b158a-5e59-4aad-8326-ea9e3954fdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655639642846_0162&quot;)</value>
      <webElementGuid>dbfab367-eea1-4740-99bd-789e46b1a9d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655639642846_0162']</value>
      <webElementGuid>f1ca9db6-3493-4f2f-aca5-3619839ca240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>dc711526-9f68-4e97-8d49-9d782db90eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/iframe</value>
      <webElementGuid>6b0c89e0-6373-4671-a938-491a39d7f0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655639642846_0162' and @name = 'lsq-form-iframe-container_1655639642846_0162']</value>
      <webElementGuid>f6080a22-fdf7-4bba-8155-2c2ac04656d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
