<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Preparing your form_lsq-form-iframe-_5f50c7</name>
   <tag></tag>
   <elementGuidId>5b8626c5-94e2-400a-bb6d-27009b035e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lsq-form-iframe-container_1655632463436_2344</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='lsq-form-iframe-container_1655632463436_2344']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2b922667-926f-47bb-ace1-fdb96004e972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsq-form-iframe-container</value>
      <webElementGuid>1d3f674d-c044-4894-a939-56c25d6d54d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655632463436_2344</value>
      <webElementGuid>bc1c6431-54e5-420d-90bb-d3eceab7fb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lsq-form-iframe-container_1655632463436_2344</value>
      <webElementGuid>3da4a9f8-24be-40d9-9e59-a9a732d75120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-form-iframe-container_1655632463436_2344&quot;)</value>
      <webElementGuid>33df6559-ad8e-45f2-b054-46f37322ee15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lsq-form-iframe-container_1655632463436_2344']</value>
      <webElementGuid>56bfa89c-e654-4411-9e22-07acce917fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-form-modal']/iframe</value>
      <webElementGuid>2b2cfec1-a5ea-4706-8c45-9fadd79efe07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/iframe</value>
      <webElementGuid>9d20e01d-932d-49ef-8b56-ce3d96f57bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lsq-form-iframe-container_1655632463436_2344' and @name = 'lsq-form-iframe-container_1655632463436_2344']</value>
      <webElementGuid>8f70b6a4-0045-41a7-bee6-c5d6d43dcbaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
