<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</name>
   <tag></tag>
   <elementGuidId>ff633e3c-7b89-4bd8-ae56-02be26f9e7d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff088a14-63d7-47d2-a605-4f01c5e24c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block </value>
      <webElementGuid>a85f788b-727d-4a7a-b244-f71d6b8565e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-control-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c627d5eb-9124-45a8-a089-dfc3f5d4de73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>65f4e2e9-c44b-4c36-90db-04f74dd619ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>019343f5-ae22-411c-9b93-7dbef4c7e7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>5a30364d-0c3b-438d-bdf5-e9de21cc8d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>acf7eee1-06a2-4107-adf2-f7e0615edef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0f0a3ac2-f865-40a0-b84d-46bebd75a7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>c3e83f7f-a98e-4af3-952d-7eaa446f47b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>743420f0-a7e0-4800-87d5-b06454f53202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0&quot;)</value>
      <webElementGuid>0aa278a5-7050-494b-9bb1-1213c16d9926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Obj_Forms_Rules_Execution/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_742ad8</value>
      <webElementGuid>838e2181-226e-4898-a9f0-4b817578a374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0']</value>
      <webElementGuid>fbb158c3-2577-44d5-aa5c-a2eb760b6d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_9deb642d-728c-4671-a6aa-83e68313187e__FirstName__Lead__0']/div/span[2]/input</value>
      <webElementGuid>6a69e389-8759-4591-b156-d40db7f6bd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>26a88c5a-02b0-4e76-9946-de305e5dff72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0' and @name = '9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0' and @type = 'text']</value>
      <webElementGuid>ef89a025-f4a9-4c16-8260-ed1850c588a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
