<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0 (2)</name>
   <tag></tag>
   <elementGuidId>1a503485-f28c-4581-b554-703b27c39d53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c7fb285-3c4b-441f-8f4f-5790bea4fc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block </value>
      <webElementGuid>ef65b3d8-6a90-48a7-afe6-e6af3159d822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-control-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>59386f71-d291-416a-aaf7-0cbdfd8ff169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>502fbe6a-5e50-4ff8-95d5-ae328e4c4b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29af0202-eff2-445c-b038-8e916b523c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>18a82b1a-a689-4b56-b454-75c7644fc76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f722be7d-0982-4cd5-9da0-e5d482c3e49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>96140b37-bbb2-48da-8173-3fbd5852fe86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>7bbbadd4-1368-427e-9f1b-5bcb0fdbc5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc809ba3-f0b6-4945-b19d-2c5dd7801c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0&quot;)</value>
      <webElementGuid>e08a08f0-4cae-41fe-914f-ec4646499079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Obj_Forms_Rules_Execution/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_141349</value>
      <webElementGuid>1f00ff20-025c-43d8-adf3-e76f3087d636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0']</value>
      <webElementGuid>dbc98991-afac-42f4-ad21-1e8b72125b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_9deb642d-728c-4671-a6aa-83e68313187e__FirstName__Lead__0']/div/span[2]/input</value>
      <webElementGuid>48619711-65b3-4b33-bed4-504bdf274e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>f4d92899-6d0b-4e9c-a9f8-ae5c0d26e07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0' and @name = '9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0' and @type = 'text']</value>
      <webElementGuid>ba4776b9-a26e-4030-8a7e-33b85cb394c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
