<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mx-custom form-control lsq-form-fiel_39aad4</name>
   <tag></tag>
   <elementGuidId>bc95da4c-f63d-4096-8b14-2ef8e3b1db00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mx-custom.form-control.lsq-form-field-ctrl-text.width-95.display-inline-block.calender-icon.lsq-flatpickr-to-init.flatpickr-date-time.flatpickr-input.input.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5f49c1d-c042-42cd-83d7-f9a3aef47b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active</value>
      <webElementGuid>83e8f846-3610-40af-ab39-96e810bc7ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a0365c1-e086-46c0-84c5-a84bd9bfe396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>135a3f06-0b94-4770-a3f9-d599dd1169a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>8895f6ef-3182-4fcb-bc6e-66c35f1ae958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FF_9deb642d-728c-4671-a6aa-83e68313187e__mx_Custom_18mx_CustomObject_8__Activity__201&quot;)/div[@class=&quot;form-group mx-custom-textfield mx-custom lsq-form-field-form-group  lsq-form-label-top&quot;]/div[@class=&quot;lsq-form-datetimepicker-container lsq-form-ctrl-field-container-block lsq-form-flatpickr&quot;]/span[@class=&quot;lsq-form-date-time-picker&quot;]/span[1]/input[@class=&quot;mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block calender-icon lsq-flatpickr-to-init flatpickr-date-time flatpickr-input input active&quot;]</value>
      <webElementGuid>789dd460-486a-4d5d-83e8-a876ccc0c6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Obj_Forms_Rules_Execution/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_742ad8</value>
      <webElementGuid>46ff1d8c-6a58-4c69-b18d-71acb9b28f6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>3699ccaf-9a48-45ea-a6e8-9f352e335210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_9deb642d-728c-4671-a6aa-83e68313187e__mx_Custom_18mx_CustomObject_8__Activity__201']/div/div/span/span/input[2]</value>
      <webElementGuid>1c90e335-93cf-4c6b-be47-4473d645d28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input[2]</value>
      <webElementGuid>c9d2f5e9-c214-4be1-b9db-1e670853eb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>70cd4410-a010-495c-bd9f-5ef55c6f69cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
