<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0 (1)</name>
   <tag></tag>
   <elementGuidId>8503c7c4-f399-4b6c-bb3b-8781fb83eb8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>695b227e-b13a-4f0b-b48f-1075e154f476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-custom form-control lsq-form-field-ctrl-text width-95 display-inline-block </value>
      <webElementGuid>9d54e8e5-7301-4770-bce0-0eedc68aa56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-control-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>53dbfab0-1bbc-4f74-956c-9a664bea5e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-schemaname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>1956d1b2-0671-4f9a-aac2-abb063dff11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc48f1e7-3cdd-4dab-99e0-c75eea5a0831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>f38960ef-a9e6-4eba-8c65-cfd5bc05db11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e6876da8-1dc6-486e-9372-bcb8a6f7bbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1f55ba09-5e39-480a-a391-85e4217db079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0</value>
      <webElementGuid>d68a8bba-37ae-47b1-88dd-7d0ee2916207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a807fd4d-c8d0-456e-8bce-2c30843291d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0&quot;)</value>
      <webElementGuid>e4efd84b-e35d-40ca-8576-1e4f1307bbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Obj_Forms_Rules_Execution/Page_Manage Forms/iframe_Preparing your form_lsq-form-iframe-_79b5c0</value>
      <webElementGuid>9cff7be1-c4e8-427c-8d3d-3d0b6a56c2c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0']</value>
      <webElementGuid>b491d8ae-cbc4-4837-8b36-dcbb16c48af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FF_9deb642d-728c-4671-a6aa-83e68313187e__FirstName__Lead__0']/div/span[2]/input</value>
      <webElementGuid>5cced378-8acc-453f-bd39-58b932fe3887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>87700ed6-b80c-4980-9d3c-bb4d88f460be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0' and @name = '9deb642d-728c-4671-a6aa-83e68313187e__tab1__section1__FirstName__Lead__0' and @type = 'text']</value>
      <webElementGuid>9b4c48c2-2a8e-4670-893a-9c58f20218f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
