<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your login details_EmailID</name>
   <tag></tag>
   <elementGuidId>73b76123-a064-46ab-801d-6d4e34859216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EmailID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d88e09c-a56a-42a5-bbcb-3ae20f2fe6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>5fd03e30-451b-4178-a60b-69a164733541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87b63688-9cb0-47f6-9466-f98881bac9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Enter a valid email address</value>
      <webElementGuid>1a723fa7-d77c-4cbf-82cd-1c13431daed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\s*((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.+]?[a-zA-Z0-9])*))[@]((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.]?[a-zA-Z0-9])*))[\.][a-zA-Z]{2,}\s*$</value>
      <webElementGuid>a8e1e49e-a800-4d1e-8c88-c4448c120124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Email address is required</value>
      <webElementGuid>942ed792-c567-45fd-aee5-b326d18370a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>6160bf56-4c04-4e92-ba65-d8d95fcb262c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e4c92f03-cd84-4379-8506-6c6fa36e891e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>f367a3e5-6e42-40f7-bfb0-f9b5de23d01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>628aa706-b91c-4a31-b488-57c201dd5117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>385421d9-388c-4c84-bf8f-78889d7345ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailID&quot;)</value>
      <webElementGuid>8064f5a1-ad83-44b0-b34b-204e7cd2961d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailID']</value>
      <webElementGuid>4320f514-ee1f-456c-8384-98ee1e01e6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='VerifyEmailForm']/input</value>
      <webElementGuid>e084cc45-2095-4548-bd07-11b5fd1ee576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9ced98e5-3431-4db0-b2c7-515ae12ccd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailID' and @name = 'EmailID' and @placeholder = 'Email address' and @type = 'text']</value>
      <webElementGuid>ade19a27-f9cb-4dfb-87b9-fcef2d5a580e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
