<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your login details_EmailID</name>
   <tag></tag>
   <elementGuidId>b12765ec-48cd-4025-8439-0b77b8643cf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EmailID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a022677-f300-41a4-996b-885e96217788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>8e0c2405-ffb0-487e-8a6b-59e763e45c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>deb8afd2-cf22-4873-8323-d82b07de2044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Enter a valid email address</value>
      <webElementGuid>7c681ef2-00c8-419e-8fa9-e8917c2edf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\s*((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.+]?[a-zA-Z0-9])*))[@]((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.]?[a-zA-Z0-9])*))[\.][a-zA-Z]{2,}\s*$</value>
      <webElementGuid>8fdb6aa0-18d8-432d-a431-ce54d964ac48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Email address is required</value>
      <webElementGuid>0b438f2a-5eb7-47fc-8162-099400012361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>d8dc6508-c36f-400e-b4c7-476aa1754bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>781cbaf3-94a6-4ef1-b6cc-9d81962a2d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>46170cba-611c-4698-9bda-0e24ff61cb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>5307fd47-e2c6-43f8-98a6-683ca06f3587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f10dd66-c2ba-4ecf-8e0f-6d9c7f58d1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailID&quot;)</value>
      <webElementGuid>676c01d9-1272-4db7-8646-444acd0409af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailID']</value>
      <webElementGuid>384265bd-5f0f-424c-b112-7e3018506a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='VerifyEmailForm']/input</value>
      <webElementGuid>d417b57b-dcd2-4b12-b3cb-14734e43f8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c302a434-f633-4807-a1aa-28f88fdaf8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailID' and @name = 'EmailID' and @placeholder = 'Email address' and @type = 'text']</value>
      <webElementGuid>82571136-4386-428c-8387-ec4da087dfae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
